#!/usr/bin/env python3
"""
Ansible inventory generator — Phase B, Layer A.

Reads plans/naming-plan.json and generates ansible/inventory/hosts.yaml.

Groups VMs by role:
    pre_k3s      — forgejo, operations (must exist before k3s bootstrap)
    k3s_servers  — k3s-server-* VMs
    k3s_workers  — k3s-worker-* VMs (empty until Phase 9)
    all_vms      — every declared VM

Usage:
    python3 generators/ansible-inventory-gen.py
    python3 generators/ansible-inventory-gen.py --plans plans/ --out ansible/inventory/
    python3 generators/ansible-inventory-gen.py --dry-run

Requires: plans/naming-plan.json
Prerequisite: readiness_validator.py must pass (not RED)
"""

import importlib.util
import json
import sys
from pathlib import Path

BOOTSTRAP_DIR = Path(__file__).parent.parent

PRE_K3S_ROLES = {"forgejo", "operations", "operations-vm", "infra-bootstrap"}
K3S_SERVER_ROLES = {"k3s-server"}
K3S_WORKER_ROLES = {"k3s-worker"}


def _load_module(rel_path: str, mod_name: str):
    spec = importlib.util.spec_from_file_location(
        mod_name, BOOTSTRAP_DIR / rel_path
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _yaml_str(value) -> str:
    """Minimal YAML scalar — no PyYAML dependency."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    s = str(value)
    if any(c in s for c in (':', '#', '[', ']', '{', '}', ',', '&', '*', '!', '|', '>')):
        return f'"{s}"'
    return s


# ---------------------------------------------------------------------------
# Generation logic (testable without filesystem)
# ---------------------------------------------------------------------------

def generate_inventory(naming_plan: dict) -> str:
    """
    Generate an Ansible inventory YAML string from a naming plan.

    Returns a YAML string suitable for writing to hosts.yaml.
    """
    cell_id = naming_plan.get("cell_id", "unknown-cell")
    search_domain = naming_plan.get("search_domain", "internal")
    generated_at = naming_plan.get("generated_at", "")

    pre_k3s: list[dict] = []
    k3s_servers: list[dict] = []
    k3s_workers: list[dict] = []
    all_vms: list[dict] = []

    for vm in naming_plan.get("vms", []):
        role = vm.get("role", vm["name"])
        entry = {
            "name": vm["name"],
            "ansible_host": vm.get("ip", "UNRESOLVED"),
            "ansible_user": "ubuntu",
            "vm_role": role,
            "cell_id": cell_id,
            "fqdn": vm.get("fqdn", f"{vm['name']}.{search_domain}"),
        }
        all_vms.append(entry)
        if role in PRE_K3S_ROLES:
            pre_k3s.append(entry)
        elif role in K3S_SERVER_ROLES:
            k3s_servers.append(entry)
        elif role in K3S_WORKER_ROLES:
            k3s_workers.append(entry)

    lines = [
        "# Ansible inventory — generated by ansible-inventory-gen.py",
        f"# Cell: {cell_id}  Generated: {generated_at}",
        "# Do not edit manually — re-run generators/ansible-inventory-gen.py",
        "",
        "all:",
        "  vars:",
        f"    cell_id: {_yaml_str(cell_id)}",
        "    ansible_python_interpreter: /usr/bin/python3",
        "",
        "  children:",
    ]

    def _emit_group(name: str, entries: list[dict], indent: int = 4) -> None:
        pad = " " * indent
        lines.append(f"{pad}{name}:")
        if not entries:
            lines.append(f"{pad}  hosts: {{}}")
            return
        lines.append(f"{pad}  hosts:")
        for e in entries:
            lines.append(f"{pad}    {e['name']}:")
            lines.append(f"{pad}      ansible_host: {_yaml_str(e['ansible_host'])}")
            lines.append(f"{pad}      ansible_user: {_yaml_str(e['ansible_user'])}")
            lines.append(f"{pad}      vm_role: {_yaml_str(e['vm_role'])}")
            lines.append(f"{pad}      fqdn: {_yaml_str(e['fqdn'])}")

    _emit_group("pre_k3s", pre_k3s)
    lines.append("")
    _emit_group("k3s_servers", k3s_servers)
    lines.append("")
    _emit_group("k3s_workers", k3s_workers)
    lines.append("")

    # all_vms flat group for plays that target every VM
    lines.append("    all_vms:")
    if not all_vms:
        lines.append("      hosts: {}")
    else:
        lines.append("      hosts:")
        for e in all_vms:
            lines.append(f"        {e['name']}:")
            lines.append(f"          ansible_host: {_yaml_str(e['ansible_host'])}")
            lines.append(f"          ansible_user: {_yaml_str(e['ansible_user'])}")
            lines.append(f"          vm_role: {_yaml_str(e['vm_role'])}")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    args = [a for a in args if a != "--dry-run"]

    plans_dir = BOOTSTRAP_DIR / "plans"
    out_dir = BOOTSTRAP_DIR.parent / "ansible" / "inventory"
    validation_dir = BOOTSTRAP_DIR / "validation"

    i = 0
    while i < len(args):
        if args[i] == "--plans" and i + 1 < len(args):
            plans_dir = Path(args[i + 1]); i += 2
        elif args[i] == "--out" and i + 1 < len(args):
            out_dir = Path(args[i + 1]); i += 2
        else:
            i += 1

    rv = _load_module("validation/readiness_validator.py", "readiness_validator")
    result = rv.run_readiness(plans_dir, validation_dir)
    if not result["ready_to_generate"]:
        print("ERROR: Readiness check FAILED — resolve RED checks before generating")
        sys.exit(1)

    naming_plan = _load_json(plans_dir / "naming-plan.json")
    inventory_yaml = generate_inventory(naming_plan)

    dest = out_dir / "hosts.yaml"
    if dry_run:
        print(f"  [dry-run] would write: {dest}")
        print(inventory_yaml)
    else:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(inventory_yaml, encoding="utf-8")
        print(f"  Written: {dest}")

    vm_count = len(naming_plan.get("vms", []))
    print(f"\nansible-inventory-gen: {vm_count} VM(s) in inventory")


if __name__ == "__main__":
    main()
