#!/usr/bin/env python3
"""
Flux bootstrap command generator — Phase B, Layer A.

Reads plans/ and metadata/ to generate a ready-to-run shell script that
bootstraps Flux CD against the cell's Forgejo instance.

The generated script:
    1. Verifies kubectl can reach the k3s cluster
    2. Creates the Flux system namespace
    3. Runs flux bootstrap gitea (or flux bootstrap git for generic Git servers)
       pointing at the platform-config repository in Forgejo

Output:
    scripts/flux-bootstrap.sh

Usage:
    python3 generators/flux-bootstrap-gen.py
    python3 generators/flux-bootstrap-gen.py --plans plans/ --out scripts/
    python3 generators/flux-bootstrap-gen.py --dry-run

Requires: plans/naming-plan.json, plans/cluster-plan.json
Prerequisite: readiness_validator.py must pass (not RED)
"""

import importlib.util
import json
import os
import sys
from pathlib import Path

BOOTSTRAP_DIR = Path(__file__).parent.parent

FLUX_VERSION = "v2.3.0"
GITEA_PROVIDER = "gitea"
PLATFORM_CONFIG_REPO = "platform-config"
CLUSTER_PATH = "clusters/homelab"
FLUX_NAMESPACE = "flux-system"
FLUX_BRANCH = "main"


def _load_module(rel_path: str, mod_name: str):
    spec = importlib.util.spec_from_file_location(
        mod_name, BOOTSTRAP_DIR / rel_path
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Generation logic (testable without filesystem)
# ---------------------------------------------------------------------------

def generate_flux_bootstrap(
    naming_plan: dict,
    cluster_plan: dict,
) -> str:
    """
    Generate the flux bootstrap shell script content.

    Returns a string containing a complete bash script.
    """
    cell_id = naming_plan.get("cell_id", "unknown-cell")
    generated_at = naming_plan.get("generated_at", "")

    # Find Forgejo VM for Git server URL
    forgejo_vm = next(
        (vm for vm in naming_plan.get("vms", []) if vm.get("role") == "forgejo"),
        None,
    )
    forgejo_ip = forgejo_vm["ip"] if forgejo_vm else "UNRESOLVED"
    forgejo_fqdn = forgejo_vm["fqdn"] if forgejo_vm else "forgejo.internal"

    # Forgejo URL — prefer FQDN but emit both
    forgejo_url = f"http://{forgejo_fqdn}"
    platform_config_repo = naming_plan.get("repository_names", {}).get(
        "platform-config", f"{cell_id}-{PLATFORM_CONFIG_REPO}"
    )

    # k3s server for kubeconfig reference
    k3s_server_vm = next(
        (vm for vm in naming_plan.get("vms", []) if vm.get("role") == "k3s-server"),
        None,
    )
    k3s_server_ip = k3s_server_vm["ip"] if k3s_server_vm else "UNRESOLVED"
    k3s_server_name = k3s_server_vm["name"] if k3s_server_vm else "k3s-server-01"

    ha_enabled = cluster_plan.get("ha", {}).get("enabled", False)
    cluster_name = f"{cell_id}-k3s"

    lines = [
        "#!/usr/bin/env bash",
        "# Flux bootstrap script",
        f"# Generated by flux-bootstrap-gen.py — {generated_at}",
        f"# Cell: {cell_id}",
        "# Do not edit manually — re-run generators/flux-bootstrap-gen.py",
        "#",
        "# Prerequisites:",
        f"#   1. k3s-server-01 ({k3s_server_ip}) is running and healthy",
        f"#   2. Forgejo ({forgejo_fqdn} / {forgejo_ip}) is accessible",
        f"#   3. Repository '{platform_config_repo}' exists in Forgejo",
        "#   4. flux CLI installed: https://fluxcd.io/flux/installation/",
        "#   5. KUBECONFIG set or ~/.kube/config populated from k3s-server",
        "#   6. GITEA_TOKEN env var set to a Forgejo personal access token",
        "#      with repo read/write access",
        "",
        "set -euo pipefail",
        "",
        "# ── Configuration ──────────────────────────────────────────────────────",
        f"CELL_ID='{cell_id}'",
        f"FORGEJO_URL='{forgejo_url}'",
        f"FORGEJO_IP='{forgejo_ip}'",
        f"PLATFORM_CONFIG_REPO='{platform_config_repo}'",
        f"CLUSTER_NAME='{cluster_name}'",
        f"FLUX_NAMESPACE='{FLUX_NAMESPACE}'",
        f"FLUX_BRANCH='{FLUX_BRANCH}'",
        f"CLUSTER_PATH='{CLUSTER_PATH}'",
        f"K3S_SERVER_IP='{k3s_server_ip}'",
        "",
        "# ── Validation ─────────────────────────────────────────────────────────",
        'if [[ -z "${GITEA_TOKEN:-}" ]]; then',
        '  echo "ERROR: GITEA_TOKEN is not set"',
        '  echo "  Create a token in Forgejo: ${FORGEJO_URL}/user/settings/applications"',
        '  exit 1',
        "fi",
        "",
        'echo "Checking cluster connectivity..."',
        "kubectl cluster-info --context default 2>/dev/null || {",
        '  echo "ERROR: Cannot reach k3s cluster at ${K3S_SERVER_IP}"',
        '  echo "  Ensure KUBECONFIG is set and the cluster is healthy"',
        '  exit 1',
        "}",
        "",
        'echo "Checking Forgejo connectivity..."',
        'curl -sf "${FORGEJO_URL}/api/v1/version" > /dev/null 2>&1 || {',
        '  echo "ERROR: Cannot reach Forgejo at ${FORGEJO_URL}"',
        '  echo "  Verify Forgejo VM is running and DNS/hosts resolves ${FORGEJO_IP}"',
        '  exit 1',
        "}",
        "",
        "# ── Flux bootstrap ─────────────────────────────────────────────────────",
        'echo "Bootstrapping Flux CD..."',
        'echo "  Repository: ${FORGEJO_URL}/${CELL_ID}/${PLATFORM_CONFIG_REPO}"',
        'echo "  Branch: ${FLUX_BRANCH}"',
        'echo "  Path: ${CLUSTER_PATH}"',
        "",
        "flux bootstrap gitea \\",
        '  --url="${FORGEJO_URL}/${CELL_ID}/${PLATFORM_CONFIG_REPO}" \\',
        '  --branch="${FLUX_BRANCH}" \\',
        '  --path="${CLUSTER_PATH}" \\',
        '  --namespace="${FLUX_NAMESPACE}" \\',
        "  --token-auth \\",
        '  --components-extra=image-reflector-controller,image-automation-controller \\',
        '  --network-policy=false',
        "  # --token-auth uses GITEA_TOKEN from environment",
        "  # --network-policy=false: simplifies initial bootstrap; tighten post-Phase 3",
        "",
        "# ── Verification ───────────────────────────────────────────────────────",
        'echo ""',
        'echo "Verifying Flux deployment..."',
        "flux check",
        "",
        'echo ""',
        'echo "Flux bootstrap complete for cell: ${CELL_ID}"',
        'echo "  Monitor reconciliation: flux get all -A"',
        'echo "  Watch sources: flux get sources all -A"',
    ]

    if ha_enabled:
        lines.extend([
            "",
            "# ── HA note ────────────────────────────────────────────────────────────",
            "# HA mode: Flux is deployed to the cluster (not a single node).",
            "# The Flux controllers will be distributed across server nodes by k3s.",
        ])

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    args = [a for a in args if a != "--dry-run"]

    plans_dir = BOOTSTRAP_DIR / "plans"
    out_dir = BOOTSTRAP_DIR / "scripts"
    validation_dir = BOOTSTRAP_DIR / "validation"

    i = 0
    while i < len(args):
        if args[i] == "--plans" and i + 1 < len(args):
            plans_dir = Path(args[i + 1]); i += 2
        elif args[i] == "--out" and i + 1 < len(args):
            out_dir = Path(args[i + 1]); i += 2
        else:
            i += 1

    rv = _load_module("validation/readiness_validator.py", "readiness_validator")
    result = rv.run_readiness(plans_dir, validation_dir)
    if not result["ready_to_generate"]:
        print("ERROR: Readiness check FAILED — resolve RED checks before generating")
        sys.exit(1)

    naming_plan = _load_json(plans_dir / "naming-plan.json")
    cluster_plan = _load_json(plans_dir / "cluster-plan.json")

    script_content = generate_flux_bootstrap(naming_plan, cluster_plan)

    dest = out_dir / "flux-bootstrap.sh"
    if dry_run:
        print(f"  [dry-run] would write: {dest}")
        print(script_content)
    else:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(script_content, encoding="utf-8")
        # Mark executable on POSIX; no-op on Windows
        try:
            dest.chmod(dest.stat().st_mode | 0o111)
        except Exception:
            pass
        print(f"  Written: {dest}")

    print(f"\nflux-bootstrap-gen: script generated for cell '{naming_plan.get('cell_id', '?')}'")


if __name__ == "__main__":
    main()
