#!/usr/bin/env python3
"""
k3s configuration generator — Phase B, Layer A.

Reads plans/ and generates k3s config.yaml for each k3s server node.
The config.yaml is placed in ansible/roles/k3s-server/files/ for deployment
by the Ansible k3s-server role.

Single-node mode (ha_enabled: false):
    One config.yaml with cluster-init omitted and embedded-registry enabled.

HA mode (ha_enabled: true):
    First server: cluster-init: true
    Additional servers: server: https://<first-server-ip>:6443

Outputs:
    ansible/roles/k3s-server/files/config.yaml        (single-node)
    ansible/roles/k3s-server/files/{vm_name}-config.yaml  (HA, one per server)

Usage:
    python3 generators/k3s-config-gen.py
    python3 generators/k3s-config-gen.py --plans plans/ --out ansible/roles/k3s-server/files/
    python3 generators/k3s-config-gen.py --dry-run

Requires: plans/naming-plan.json, plans/cluster-plan.json
Prerequisite: readiness_validator.py must pass (not RED)
"""

import importlib.util
import json
import os
import sys
from pathlib import Path

BOOTSTRAP_DIR = Path(__file__).parent.parent


def _load_module(rel_path: str, mod_name: str):
    spec = importlib.util.spec_from_file_location(
        mod_name, BOOTSTRAP_DIR / rel_path
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _load_yaml_minimal(path: Path) -> dict:
    try:
        import yaml
        with open(path, encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    except ImportError:
        pass
    result = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        clean = line.split("#")[0].strip()
        if ":" in clean and not clean.startswith("-"):
            k, _, v = clean.partition(":")
            v = v.strip().strip('"').strip("'")
            if v and "POPULATE" not in v:
                try:
                    result[k.strip()] = int(v)
                except ValueError:
                    result[k.strip()] = v
    return result


K3S_ROLE = "k3s-server"


# ---------------------------------------------------------------------------
# Generation logic (testable without filesystem)
# ---------------------------------------------------------------------------

def generate_k3s_configs(
    naming_plan: dict,
    cluster_plan: dict,
    k3s_meta: dict | None = None,
) -> dict[str, str]:
    """
    Generate k3s config.yaml content for each server node.

    Returns dict keyed by output filename:
        {
            "config.yaml": "...",                    # single-node
            # or
            "k3s-server-01-config.yaml": "...",      # HA first server
            "k3s-server-02-config.yaml": "...",      # HA additional
        }
    """
    k3s_meta = k3s_meta or {}
    ha_enabled = cluster_plan.get("ha", {}).get("enabled", False)
    cell_id = naming_plan.get("cell_id", "unknown-cell")
    search_domain = naming_plan.get("search_domain", "internal")
    generated_at = naming_plan.get("generated_at", "")

    # Extract networking from k3s_meta or defaults
    networking = k3s_meta.get("networking") or {}
    if not isinstance(networking, dict):
        networking = {}
    pod_cidr = networking.get("pod_cidr", "10.42.0.0/16")
    service_cidr = networking.get("service_cidr", "10.43.0.0/16")
    cluster_name = k3s_meta.get("cluster_name", f"{cell_id}-k3s")

    # Collect k3s server VMs from naming plan
    server_vms = [
        vm for vm in naming_plan.get("vms", [])
        if vm.get("role") == K3S_ROLE
    ]

    if not server_vms:
        return {"config.yaml": f"# No k3s server VMs found in naming plan\n# Cell: {cell_id}\n"}

    result: dict[str, str] = {}

    header = (
        f"# k3s config.yaml\n"
        f"# Generated by k3s-config-gen.py — {generated_at}\n"
        f"# Cell: {cell_id}\n"
        f"# Do not edit manually — re-run generators/k3s-config-gen.py\n"
    )

    def _make_config(vm: dict, is_first_server: bool, first_server_ip: str) -> str:
        ip = vm.get("ip", "UNRESOLVED")
        name = vm["name"]
        fqdn = vm.get("fqdn", f"{name}.{search_domain}")

        tls_sans = [ip, fqdn, name]
        if ha_enabled and first_server_ip not in tls_sans:
            tls_sans.append(first_server_ip)

        lines = [header, ""]
        lines.append(f"cluster-name: {cluster_name}")
        lines.append(f"node-name: {name}")
        lines.append(f"node-ip: {ip}")
        lines.append("")
        lines.append("tls-san:")
        for san in tls_sans:
            lines.append(f"  - {san}")
        lines.append("")

        if ha_enabled:
            if is_first_server:
                lines.append("cluster-init: true")
            else:
                lines.append(f"server: https://{first_server_ip}:6443")
            lines.append("embedded-registry: false")
        else:
            # Single-node: embedded registry for local image caching
            lines.append("embedded-registry: true")
            lines.append("disable:")
            lines.append("  - traefik")
            lines.append("    # reason: ingress-nginx deployed via Flux replaces Traefik")

        lines.append("")
        lines.append(f"cluster-cidr: {pod_cidr}")
        lines.append(f"service-cidr: {service_cidr}")
        lines.append("flannel-backend: vxlan")
        lines.append("")
        lines.append("write-kubeconfig-mode: \"0644\"")
        lines.append("secrets-encryption: true")
        lines.append("")
        lines.append("# etcd snapshots")
        lines.append("etcd-snapshot-schedule-cron: \"0 * * * *\"")
        lines.append("etcd-snapshot-retention: 5")
        lines.append("")
        lines.append("kubelet-arg:")
        lines.append("  - \"max-pods=110\"")
        lines.append("")

        return "\n".join(lines)

    if not ha_enabled:
        vm = server_vms[0]
        config_content = _make_config(vm, is_first_server=True, first_server_ip=vm.get("ip", ""))
        result["config.yaml"] = config_content
    else:
        first_ip = server_vms[0].get("ip", "UNRESOLVED")
        for idx, vm in enumerate(server_vms):
            config_content = _make_config(vm, is_first_server=(idx == 0), first_server_ip=first_ip)
            result[f"{vm['name']}-config.yaml"] = config_content

    return result


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    args = [a for a in args if a != "--dry-run"]

    plans_dir = BOOTSTRAP_DIR / "plans"
    out_dir = BOOTSTRAP_DIR.parent / "ansible" / "roles" / "k3s-server" / "files"
    validation_dir = BOOTSTRAP_DIR / "validation"
    k3s_meta_path = BOOTSTRAP_DIR / "metadata" / "k3s-cluster.yaml"

    i = 0
    while i < len(args):
        if args[i] == "--plans" and i + 1 < len(args):
            plans_dir = Path(args[i + 1]); i += 2
        elif args[i] == "--out" and i + 1 < len(args):
            out_dir = Path(args[i + 1]); i += 2
        elif args[i] == "--k3s-meta" and i + 1 < len(args):
            k3s_meta_path = Path(args[i + 1]); i += 2
        else:
            i += 1

    rv = _load_module("validation/readiness_validator.py", "readiness_validator")
    result = rv.run_readiness(plans_dir, validation_dir)
    if not result["ready_to_generate"]:
        print("ERROR: Readiness check FAILED — resolve RED checks before generating")
        sys.exit(1)

    naming_plan = _load_json(plans_dir / "naming-plan.json")
    cluster_plan = _load_json(plans_dir / "cluster-plan.json")
    k3s_meta = _load_yaml_minimal(k3s_meta_path) if k3s_meta_path.exists() else {}

    outputs = generate_k3s_configs(naming_plan, cluster_plan, k3s_meta)

    for filename, content in outputs.items():
        dest = out_dir / filename
        if dry_run:
            print(f"  [dry-run] would write: {dest}")
            print(content)
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
            print(f"  Written: {dest}")

    print(f"\nk3s-config-gen: {len(outputs)} config file(s) generated")


if __name__ == "__main__":
    main()
