#!/usr/bin/env python3
"""
lib/forge-render-docs.py — Convert Markdown docs to styled HTML.

Produces the same dark-themed, browser-viewable HTML as docs/ARCHITECTURE.html
from any Markdown source (ARCHITECTURE.md, README.md, etc.).

Dependencies: stdlib only (no pip install required).

Usage:
  python3 lib/forge-render-docs.py \
      --input ARCHITECTURE.md \
      --output docs/ARCHITECTURE.html \
      [--title "Broodforge Architecture"]

  python3 lib/forge-render-docs.py \
      --input README.md \
      --output docs/README.html

Exit codes:
  0 — HTML written
  1 — error
"""

import argparse
import html
import re
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Minimal Markdown → HTML converter (stdlib only)
# ---------------------------------------------------------------------------

_CSS = """
:root {
  --bg:#1a1d23; --bg2:#22262e; --bg3:#2a2f3a; --border:#3a3f4d;
  --text:#cdd6f4; --muted:#7f8498; --accent:#89b4fa; --green:#a6e3a1;
  --yellow:#f9e2af; --orange:#fab387; --red:#f38ba8; --forge-h:#cba6f7;
  --spawn-h:#89dceb; --phoenix-h:#fab387; --code-bg:#181b21; --radius:6px;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  background: var(--bg); color: var(--text);
  font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
  font-size: 14px; line-height: 1.7; padding: 28px 32px;
  max-width: 1100px; margin: 0 auto;
}
h1 { color: var(--accent); font-size: 1.8em; margin: 8px 0 6px; }
h2 {
  color: var(--accent); font-size: 1.05em; margin: 28px 0 8px;
  text-transform: uppercase; letter-spacing: .05em;
  border-bottom: 1px solid var(--border); padding-bottom: 5px;
}
h3 { color: var(--accent); font-size: .95em; margin: 18px 0 6px; }
h4 {
  color: var(--muted); font-size: .82em; margin: 12px 0 4px;
  text-transform: uppercase; letter-spacing: .08em;
}
.subtitle { color: var(--muted); margin-bottom: 6px; font-size: .95em; }
.meta { color: var(--muted); font-size: .8em; margin-bottom: 24px; }
p { margin: 8px 0; }
ul, ol { margin: 8px 0 8px 20px; }
li { margin: 4px 0; }
code {
  background: var(--code-bg); color: var(--green);
  padding: 1px 5px; border-radius: 3px;
  font-family: 'Cascadia Code','Fira Code',Consolas,monospace; font-size: .9em;
}
pre {
  background: var(--code-bg); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 12px 16px; overflow-x: auto;
  margin: 10px 0; font-family: 'Cascadia Code','Fira Code',Consolas,monospace;
  font-size: .85em; color: var(--green); white-space: pre;
}
pre code { background: none; padding: 0; border-radius: 0; font-size: inherit; }
table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: .88em; }
th {
  background: var(--bg2); color: var(--muted); text-align: left;
  padding: 6px 10px; border-bottom: 1px solid var(--border);
  font-weight: 600; font-size: .8em; text-transform: uppercase; letter-spacing: .05em;
}
td { padding: 5px 10px; border-bottom: 1px solid var(--bg3); vertical-align: top; }
tr:hover td { background: var(--bg2); }
hr { border: none; border-top: 1px solid var(--border); margin: 20px 0; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
strong { color: #e0e6f5; font-weight: 600; }
em { color: var(--muted); font-style: italic; }
blockquote {
  border-left: 3px solid var(--border); padding: 4px 12px;
  color: var(--muted); margin: 10px 0; background: var(--bg2);
  border-radius: 0 var(--radius) var(--radius) 0;
}
.toc-header {
  font-size: .75em; text-transform: uppercase; letter-spacing: .1em;
  color: var(--muted); margin-bottom: 6px;
}
.toc { background: var(--bg2); border: 1px solid var(--border); border-radius: var(--radius);
  padding: 14px 18px; margin: 16px 0 24px; max-width: 480px; }
.toc a { font-size: .88em; display: block; padding: 2px 0; color: var(--accent); }
.toc a.toc-h3 { padding-left: 16px; color: var(--muted); font-size: .83em; }
.badge {
  display: inline-block; padding: 1px 7px; border-radius: 10px;
  font-size: .75em; font-weight: 600; margin-left: 8px; vertical-align: middle;
}
.badge-green { background: #1e3a2b; color: var(--green); }
.badge-yellow { background: #3a3017; color: var(--yellow); }
.badge-orange { background: #3a2410; color: var(--orange); }
.badge-red { background: #3a1019; color: var(--red); }
.updated-note { color: var(--muted); font-size: .75em; text-align: right; margin-top: 24px; }
"""

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
{body}
<p class="updated-note">Generated by forge-render-docs.py · {generated_at}</p>
</body>
</html>"""


def _escape(text: str) -> str:
    """HTML-escape text (for use inside tags, not pre blocks)."""
    return html.escape(text, quote=False)


def _inline(text: str) -> str:
    """Convert inline Markdown elements to HTML."""
    # Inline code: `code`
    text = re.sub(r'`([^`]+)`', lambda m: f'<code>{_escape(m.group(1))}</code>', text)
    # Bold+italic: ***text*** or ___text___
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<strong><em>\1</em></strong>', text)
    # Bold: **text** or __text__
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'__(.+?)__', r'<strong>\1</strong>', text)
    # Italic: *text* or _text_
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    text = re.sub(r'(?<![a-zA-Z0-9])_([^_]+)_(?![a-zA-Z0-9])', r'<em>\1</em>', text)
    # Links: [text](url)
    text = re.sub(
        r'\[([^\]]+)\]\(([^)]+)\)',
        lambda m: f'<a href="{_escape(m.group(2))}">{m.group(1)}</a>',
        text
    )
    return text


def _slugify(text: str) -> str:
    """Convert heading text to an HTML anchor id."""
    s = text.lower()
    s = re.sub(r'[^a-z0-9\s-]', '', s)
    s = re.sub(r'\s+', '-', s.strip())
    return s


def _render_table(rows: list[str]) -> str:
    """Render a Markdown table to HTML."""
    if len(rows) < 2:
        return ""
    headers = [c.strip() for c in rows[0].strip('|').split('|')]
    # rows[1] is the separator line — skip
    html_rows = []
    for row in rows[2:]:
        cells = [c.strip() for c in row.strip('|').split('|')]
        cells += [''] * (len(headers) - len(cells))  # pad
        html_rows.append('<tr>' + ''.join(
            f'<td>{_inline(_escape(c))}</td>' for c in cells[:len(headers)]
        ) + '</tr>')
    head = '<thead><tr>' + ''.join(
        f'<th>{_inline(_escape(h))}</th>' for h in headers
    ) + '</tr></thead>'
    body = '<tbody>' + ''.join(html_rows) + '</tbody>'
    return f'<table>{head}{body}</table>'


def convert_md_to_html(md_text: str, title: str = "", generated_at: str = "") -> str:
    """Convert full Markdown text to a styled HTML document."""
    from datetime import datetime, timezone

    if not generated_at:
        generated_at = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')

    lines = md_text.splitlines()
    body_parts: list[str] = []
    headings: list[tuple[int, str, str]] = []  # (level, text, slug) for ToC

    i = 0
    n = len(lines)

    # Collect paragraph buffer
    para_buf: list[str] = []

    def flush_para():
        if para_buf:
            joined = ' '.join(para_buf).strip()
            if joined:
                body_parts.append(f'<p>{_inline(_escape(joined))}</p>')
            para_buf.clear()

    while i < n:
        line = lines[i]

        # Fenced code block
        if line.startswith('```'):
            flush_para()
            lang = line[3:].strip()
            code_lines = []
            i += 1
            while i < n and not lines[i].startswith('```'):
                code_lines.append(lines[i])
                i += 1
            code_content = html.escape('\n'.join(code_lines))
            lang_class = f' class="language-{lang}"' if lang else ''
            body_parts.append(f'<pre><code{lang_class}>{code_content}</code></pre>')
            i += 1
            continue

        # Horizontal rule
        if re.match(r'^(\-{3,}|\*{3,}|_{3,})\s*$', line):
            flush_para()
            body_parts.append('<hr>')
            i += 1
            continue

        # Headings
        m = re.match(r'^(#{1,6})\s+(.*)', line)
        if m:
            flush_para()
            level = len(m.group(1))
            text = m.group(2).strip()
            slug = _slugify(text)
            headings.append((level, text, slug))
            tag = f'h{level}'
            body_parts.append(
                f'<{tag} id="{slug}">{_inline(_escape(text))}</{tag}>'
            )
            i += 1
            continue

        # Table detection
        if '|' in line and i + 1 < n and re.match(r'^[\|\s\-:]+$', lines[i + 1]):
            flush_para()
            table_rows = [line]
            i += 1
            while i < n and '|' in lines[i]:
                table_rows.append(lines[i])
                i += 1
            body_parts.append(_render_table(table_rows))
            continue

        # Blockquote
        if line.startswith('>'):
            flush_para()
            content = line.lstrip('> ')
            body_parts.append(f'<blockquote>{_inline(_escape(content))}</blockquote>')
            i += 1
            continue

        # Unordered list
        if re.match(r'^(\s*[-*+])\s', line):
            flush_para()
            items = []
            indent0 = len(line) - len(line.lstrip())
            while i < n and re.match(r'^\s*[-*+]\s', lines[i]):
                item_line = lines[i]
                indent = len(item_line) - len(item_line.lstrip())
                text_content = re.sub(r'^\s*[-*+]\s+', '', item_line)
                items.append((indent, text_content))
                i += 1
            # Simple flat list (no nesting for now)
            li_tags = ''.join(
                f'<li style="padding-left:{max(0,ind - indent0)*2}px">'
                f'{_inline(_escape(t))}</li>'
                for ind, t in items
            )
            body_parts.append(f'<ul>{li_tags}</ul>')
            continue

        # Ordered list
        if re.match(r'^\s*\d+\.\s', line):
            flush_para()
            items = []
            while i < n and re.match(r'^\s*\d+\.\s', lines[i]):
                text_content = re.sub(r'^\s*\d+\.\s+', '', lines[i])
                items.append(text_content)
                i += 1
            li_tags = ''.join(f'<li>{_inline(_escape(t))}</li>' for t in items)
            body_parts.append(f'<ol>{li_tags}</ol>')
            continue

        # Blank line — flush paragraph
        if not line.strip():
            flush_para()
            i += 1
            continue

        # Regular paragraph line — accumulate
        para_buf.append(line)
        i += 1

    flush_para()

    # Build ToC from h2 and h3 headings
    toc_items = []
    for level, text, slug in headings:
        if level == 2:
            toc_items.append(f'<a href="#{slug}">{_escape(text)}</a>')
        elif level == 3:
            toc_items.append(f'<a href="#{slug}" class="toc-h3">{_escape(text)}</a>')

    toc_html = ""
    if toc_items:
        toc_html = (
            '<div class="toc">'
            '<div class="toc-header">Contents</div>'
            + ''.join(toc_items)
            + '</div>'
        )

    # Inject ToC after first h1
    body_str = '\n'.join(body_parts)
    h1_match = re.search(r'(<h1[^>]*>.*?</h1>)', body_str)
    if h1_match and toc_html:
        insert_at = h1_match.end()
        body_str = body_str[:insert_at] + '\n' + toc_html + body_str[insert_at:]

    # Infer title from first h1
    if not title:
        m = re.search(r'<h1[^>]*>([^<]+)</h1>', body_str)
        title = m.group(1) if m else "Broodforge Documentation"

    return _HTML_TEMPLATE.format(
        title=_escape(title),
        css=_CSS,
        body=body_str,
        generated_at=_escape(generated_at),
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert Markdown docs to styled dark-theme HTML"
    )
    parser.add_argument("--input",  required=True, help="Input Markdown file")
    parser.add_argument("--output", required=True, help="Output HTML file")
    parser.add_argument("--title",  default="",    help="Page title (default: from first H1)")
    args = parser.parse_args(argv)

    src = Path(args.input)
    dst = Path(args.output)

    if not src.exists():
        print(f"[render-docs] ERROR: input file not found: {src}", file=sys.stderr)
        return 1

    md_text = src.read_text(encoding="utf-8")
    html_out = convert_md_to_html(md_text, title=args.title)

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(html_out, encoding="utf-8")
    print(f"[render-docs] Written: {dst}  ({len(html_out):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
